import '../../marketing.css';
import PgHeader from '../../components/pg/PgHeader';
import PgFooter from '../../components/pg/PgFooter';

export default function Privacy() {
  return (
    <div className="pub-site">
      <PgHeader />
      <div className="pg-container">
        <div className="pg-legal-page">
          <h1>Privacy Policy</h1>
          <p className="pg-updated">Last updated: January 2026</p>

          <p>
            Harborlight Credit Union ("Harborlight," "we," "us") respects your privacy. This policy describes what
            information we collect, how we use it, and the choices you have.
          </p>

          <h2>Information we collect</h2>
          <ul>
            <li>Information you provide when you open an account, apply for a loan, or contact customer care</li>
            <li>Account and transaction information generated by your use of our services</li>
            <li>Device and usage information when you access online or mobile banking</li>
          </ul>

          <h2>How we use it</h2>
          <ul>
            <li>To provide and service your accounts and transactions</li>
            <li>To evaluate loan and membership applications</li>
            <li>To detect and prevent fraud and unauthorized activity</li>
            <li>To comply with applicable laws and regulations</li>
          </ul>

          <h2>How we protect it</h2>
          <p>
            We use industry-standard safeguards, including encryption in transit, password hashing, rate limiting,
            and role-based administrative access, to protect your information. We never ask for your online banking
            password, PIN, or security-question answers outside of our authenticated login flow.
          </p>

          <h2>Your choices</h2>
          <p>
            You may contact customer care at any time to ask what information we hold about you or to request
            corrections, subject to our recordkeeping obligations as a financial institution.
          </p>

          <h2>Contact us</h2>
          <p>Questions about this policy can be directed to our customer care team from the homepage.</p>
        </div>
      </div>
      <PgFooter />
    </div>
  );
}
